In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from scipy import stats

### Задача 1.

#### Даны матрица объект-признак и значения целевой переменной.
#### Подберите два признака (из четырёх) так, чтобы уровень линейной зависимости целевой переменной от значений этих признаков был максимальным. Другими словами, модель линейной регрессии на этих признаках должна давать наилучший результат. В качестве ответа запишите значение коэффициента детерминации для модели на этих признаках.

In [2]:
X = [[ 1.22401313,  2.30868478,  3.03636353,  2.69287214],
     [-0.18757272,  1.30337355,  5.12093014,  3.46363202],
     [-0.81094525,  1.82463398,  5.79686488,  1.86159445],
     [ 0.75129018,  2.67392052,  3.65529809,  1.66746094],
     [ 0.00972362,  1.97367255,  2.50594319,  1.69755173],
     [-0.62972637,  0.77750764,  2.84124027,  4.54410559],
     [ 2.29536229,  1.81206697,  1.95026215,  1.51874636],
     [ 0.0920418 ,  2.26971361,  7.47708735,  2.61081203],
     [ 2.39252799,  3.17563985,  3.61420599,  5.10773362],
     [ 0.54983815,  2.87988651,  1.65752765,  1.59635987]]

In [3]:
y = np.array([ 9.26193358,  9.700363  ,  8.67214805,  8.74796974,  6.18689108,
               7.53312713,  7.57643777, 12.44965478, 14.29010746,  6.68361218])

In [4]:
X = pd.DataFrame(X, columns=['1', '2', '3', '4'])

X

1         2         3         4
0  1.224013  2.308685  3.036364  2.692872
1 -0.187573  1.303374  5.120930  3.463632
2 -0.810945  1.824634  5.796865  1.861594
3  0.751290  2.673921  3.655298  1.667461
4  0.009724  1.973673  2.505943  1.697552
5 -0.629726  0.777508  2.841240  4.544106
6  2.295362  1.812067  1.950262  1.518746
7  0.092042  2.269714  7.477087  2.610812
8  2.392528  3.175640  3.614206  5.107734
9  0.549838  2.879887  1.657528  1.596360

In [5]:
# возьмём признаки 1 и 2:

x_12 = X[['1', '2']].values

x_12

array([[ 1.22401313,  2.30868478],
       [-0.18757272,  1.30337355],
       [-0.81094525,  1.82463398],
       [ 0.75129018,  2.67392052],
       [ 0.00972362,  1.97367255],
       [-0.62972637,  0.77750764],
       [ 2.29536229,  1.81206697],
       [ 0.0920418 ,  2.26971361],
       [ 2.39252799,  3.17563985],
       [ 0.54983815,  2.87988651]])

In [6]:
# выполним необходимые расчёты для признаков 1 и 2

In [7]:
ones_12 = np.ones((x_12.shape[0], 1))
x_12 = np.hstack((ones_12, x_12))

In [8]:
XTX_12 = x_12.T.dot(x_12)
XTX_inv_12 = np.linalg.inv(XTX_12)
b_12 = XTX_inv_12.dot(x_12.T).dot(y)

print(b_12)

[6.70781579 0.40786841 1.03360247]


In [9]:
z_12 = x_12.dot(b_12)
e_12 = y - z_12

e_12

array([-0.33138079,  1.72188207,  0.40914502, -1.03004444, -2.56488349,
        0.27852302, -1.94054069,  3.35831645,  3.32410589, -3.22512304])

In [10]:
lr_12 = LinearRegression(fit_intercept=False).fit(x_12, y)

In [11]:
b_12, lr_12.coef_

(array([6.70781579, 0.40786841, 1.03360247]),
 array([6.70781579, 0.40786841, 1.03360247]))

In [12]:
# посчитаем R^2:

R2_12 = round(1 - ((e_12 - e_12.mean()) ** 2).sum() / ((y - y.mean()) ** 2).sum(), 8)

R2_12

0.18113595

In [13]:
# возьмём признаки 1 и 3:

x_13 = X[['1', '3']].values

x_13

array([[ 1.22401313,  3.03636353],
       [-0.18757272,  5.12093014],
       [-0.81094525,  5.79686488],
       [ 0.75129018,  3.65529809],
       [ 0.00972362,  2.50594319],
       [-0.62972637,  2.84124027],
       [ 2.29536229,  1.95026215],
       [ 0.0920418 ,  7.47708735],
       [ 2.39252799,  3.61420599],
       [ 0.54983815,  1.65752765]])

In [14]:
# выполним необходимые расчёты для признаков 1 и 3

In [15]:
ones_13 = np.ones((x_13.shape[0], 1))
x_13 = np.hstack((ones_13, x_13))

In [16]:
XTX_13 = x_13.T.dot(x_13)
XTX_inv_13 = np.linalg.inv(XTX_13)
b_13 = XTX_inv_13.dot(x_13.T).dot(y)

print(b_13)

[3.62455695 1.62531203 1.21134979]


In [17]:
z_13 = x_13.dot(b_13)
e_13 = y - z_13

e_13

array([-0.03012497,  0.17743258, -0.6564009 , -0.52551276, -0.48904355,
        1.49033621, -2.14124878, -0.38186703,  2.3988783 ,  0.15755089])

In [18]:
lr_13 = LinearRegression(fit_intercept=False).fit(x_13, y)

In [19]:
b_13, lr_13.coef_

(array([3.62455695, 1.62531203, 1.21134979]),
 array([3.62455695, 1.62531203, 1.21134979]))

In [20]:
# посчитаем R^2:

R2_13 = round(1 - ((e_13 - e_13.mean()) ** 2).sum() / ((y - y.mean()) ** 2).sum(), 8)

R2_13

0.76342462

In [21]:
# возьмём признаки 1 и 4:

x_14 = X[['1', '4']].values

x_14

array([[ 1.22401313,  2.69287214],
       [-0.18757272,  3.46363202],
       [-0.81094525,  1.86159445],
       [ 0.75129018,  1.66746094],
       [ 0.00972362,  1.69755173],
       [-0.62972637,  4.54410559],
       [ 2.29536229,  1.51874636],
       [ 0.0920418 ,  2.61081203],
       [ 2.39252799,  5.10773362],
       [ 0.54983815,  1.59635987]])

In [22]:
# выполним необходимые расчёты для признаков 1 и 4

In [23]:
ones_14 = np.ones((x_14.shape[0], 1))
x_14 = np.hstack((ones_14, x_14))

In [24]:
XTX_14 = x_14.T.dot(x_14)
XTX_inv_14 = np.linalg.inv(XTX_14)
b_14 = XTX_inv_14.dot(x_14.T).dot(y)

print(b_14)

[5.70686123 0.68359949 1.12650707]


In [25]:
z_14 = x_14.dot(b_14)
e_14 = y - z_14

e_14

array([-0.3152019 ,  0.21992042,  1.42254926,  0.64912039, -1.43892124,
       -2.86222056, -1.41041046,  3.73877561,  1.19381729, -1.19742881])

In [26]:
lr_14 = LinearRegression(fit_intercept=False).fit(x_14, y)

In [27]:
b_14, lr_14.coef_

(array([5.70686123, 0.68359949, 1.12650707]),
 array([5.70686123, 0.68359949, 1.12650707]))

In [28]:
# посчитаем R^2:

R2_14 = round(1 - ((e_14 - e_14.mean()) ** 2).sum() / ((y - y.mean()) ** 2).sum(), 8)

R2_14

0.45329668

In [29]:
# возьмём признаки 2 и 3:

x_23 = X[['2', '3']].values

x_23

array([[2.30868478, 3.03636353],
       [1.30337355, 5.12093014],
       [1.82463398, 5.79686488],
       [2.67392052, 3.65529809],
       [1.97367255, 2.50594319],
       [0.77750764, 2.84124027],
       [1.81206697, 1.95026215],
       [2.26971361, 7.47708735],
       [3.17563985, 3.61420599],
       [2.87988651, 1.65752765]])

In [30]:
# выполним необходимые расчёты для признаков 2 и 3

In [31]:
ones_23 = np.ones((x_23.shape[0], 1))
x_23 = np.hstack((ones_23, x_23))

In [32]:
XTX_23 = x_23.T.dot(x_23)
XTX_inv_23 = np.linalg.inv(XTX_23)
b_23 = XTX_inv_23.dot(x_23.T).dot(y)

print(b_23)

[2.48896193 1.60611956 0.86269915]


In [33]:
z_23 = x_23.dot(b_23)
e_23 = y - z_23

e_23

array([ 0.44547964,  0.70020526, -1.74834459, -1.18905078, -1.63389999,
        1.34425942,  0.49459014, -0.13521545,  3.58271583, -1.86073949])

In [34]:
lr_23 = LinearRegression(fit_intercept=False).fit(x_23, y)

In [35]:
b_23, lr_23.coef_

(array([2.48896193, 1.60611956, 0.86269915]),
 array([2.48896193, 1.60611956, 0.86269915]))

In [36]:
# посчитаем R^2:

R2_23 = round(1 - ((e_23 - e_23.mean()) ** 2).sum() / ((y - y.mean()) ** 2).sum(), 8)

R2_23

0.54794827

In [37]:
# возьмём признаки 2 и 4:

x_24 = X[['2', '4']].values

x_24

array([[2.30868478, 2.69287214],
       [1.30337355, 3.46363202],
       [1.82463398, 1.86159445],
       [2.67392052, 1.66746094],
       [1.97367255, 1.69755173],
       [0.77750764, 4.54410559],
       [1.81206697, 1.51874636],
       [2.26971361, 2.61081203],
       [3.17563985, 5.10773362],
       [2.87988651, 1.59635987]])

In [38]:
# выполним необходимые расчёты для признаков 2 и 4

In [39]:
ones_24 = np.ones((x_24.shape[0], 1))
x_24 = np.hstack((ones_24, x_24))

In [40]:
XTX_24 = x_24.T.dot(x_24)
XTX_inv_24 = np.linalg.inv(XTX_24)
b_24 = XTX_inv_24.dot(x_24.T).dot(y)

print(b_24)

[1.91685221 1.74373667 1.31971882]


In [41]:
z_24 = x_24.dot(b_24)
e_24 = y - z_24

e_24

array([-0.23449097,  0.93975019,  1.11683344, -0.03207531, -1.41181729,
       -1.73643531,  0.49549979,  3.12948196,  0.09500343, -2.3617499 ])

In [42]:
lr_24 = LinearRegression(fit_intercept=False).fit(x_24, y)

In [43]:
b_24, lr_24.coef_

(array([1.91685221, 1.74373667, 1.31971882]),
 array([1.91685221, 1.74373667, 1.31971882]))

In [44]:
# посчитаем R^2:

R2_24 = round(1 - ((e_24 - e_24.mean()) ** 2).sum() / ((y - y.mean()) ** 2).sum(), 8)

R2_24

0.60620558

In [45]:
# возьмём признаки 3 и 4:

x_34 = X[['3', '4']].values

x_34

array([[3.03636353, 2.69287214],
       [5.12093014, 3.46363202],
       [5.79686488, 1.86159445],
       [3.65529809, 1.66746094],
       [2.50594319, 1.69755173],
       [2.84124027, 4.54410559],
       [1.95026215, 1.51874636],
       [7.47708735, 2.61081203],
       [3.61420599, 5.10773362],
       [1.65752765, 1.59635987]])

In [46]:
# выполним необходимые расчёты для признаков 3 и 4

In [47]:
ones_34 = np.ones((x_34.shape[0], 1))
x_34 = np.hstack((ones_34, x_34))

In [48]:
XTX_34 = x_34.T.dot(x_34)
XTX_inv_34 = np.linalg.inv(XTX_34)
b_34 = XTX_inv_34.dot(x_34.T).dot(y)

print(b_34)

[3.64001086 0.70753914 1.04851745]


In [49]:
z_34 = x_34.dot(b_34)
e_34 = y - z_34

e_34

array([ 0.65005323, -1.19458502, -1.0212859 ,  0.7733305 , -1.0060853 ,
       -2.88174646,  0.96410803,  0.78182995,  2.73735653,  0.19702444])

In [50]:
lr_34 = LinearRegression(fit_intercept=False).fit(x_34, y)

In [51]:
b_34, lr_34.coef_

(array([3.64001086, 0.70753914, 1.04851745]),
 array([3.64001086, 0.70753914, 1.04851745]))

In [52]:
# посчитаем R^2:

R2_34 = round(1 - ((e_34 - e_34.mean()) ** 2).sum() / ((y - y.mean()) ** 2).sum(), 8)

R2_34

0.62244199

In [53]:
# посмотрим на все получившиеся R^2:

print(f'R^2 с признаками 1 и 2: {R2_12}\nR^2 с признаками 1 и 3: {R2_13}\n'
      f'R^2 с признаками 1 и 4: {R2_14}\nR^2 с признаками 2 и 3: {R2_23}\n'
      f'R^2 с признаками 2 и 4: {R2_24}\nR^2 с признаками 3 и 4: {R2_34}')

R^2 с признаками 1 и 2: 0.18113595
R^2 с признаками 1 и 3: 0.76342462
R^2 с признаками 1 и 4: 0.45329668
R^2 с признаками 2 и 3: 0.54794827
R^2 с признаками 2 и 4: 0.60620558
R^2 с признаками 3 и 4: 0.62244199


In [54]:
# модель линейной регрессии на признаках 1 и 3 даёт наилучший результат.

print(f'Ответ: {R2_13}')

Ответ: 0.76342462


### Задача 2.

#### Является ли значимым уравнение регрессии, полученное в предыдущей задаче? В качестве ответа запишите 1, если является, и 0 иначе.

In [55]:
n = x_13.shape[0] # число наблюдений
m = x_13.shape[1] - 1 # число факторов (вычитаем единицу, так как добавляли нулевой фактор)

# параметры k1 и k2:

k1 = m
k2 = n - m - 1

k1, k2

(2, 7)

In [56]:
alpha = 0.05 # уровень значимости

# найдём квантиль:

t = stats.f.ppf(1 - alpha, k1, k2)

t

4.73741412777588

In [57]:
# считаем значение статистики по F-тесту Фишера:

F = (R2_13 / k1) / ((1 - R2_13) / k2)

F

11.29443888032643

In [58]:
# видим, что статистика попадает в критическую область (F > t), H0 отвергается, уравнение признаётся значимым.

if F > t:
    print('Ответ: 1')
elif F < t:
    print('Ответ: 0')

Ответ: 1


### Задача 3.

#### Для проведения A/B-тестирования сайта интернет-магазина были получены следующие данные: страница A была посещена 2509 раз, из них 77 закончились совершением покупки, страница B была посещена 1465 раз, 60 из них закончились совершением покупки. Является ли значимым отличие конверсии на страницах A и B? В качестве ответа запишите 1, если является, и 0 иначе.
#### Подсказка: реализуйте двухвыборочный t-тест. В качестве выборок здесь можно взять наборы меток совершения покупки (0 или 1) каждым посетителем.

In [59]:
# создадим выборки с метками:

a = np.concatenate((np.ones(77, dtype=np.int64), np.zeros(2432, dtype=np.int64)), axis=0)
b = np.concatenate((np.ones(60, dtype=np.int64), np.zeros(1405, dtype=np.int64)), axis=0)

In [60]:
# перемешаем для рандомности:

np.random.shuffle(a)
np.random.shuffle(b)

In [61]:
n1 = a.size # объём выборки A
n2 = b.size # объём выборки B

s1 = a.std(ddof=1) # среднее квадратическое отклонение выборки A
s2 = b.std(ddof=1) # среднее квадратическое отклонение выборки B

print(f'Объём выборки A: {n1}\nОбъём выборки B: {n2}\n'
      f'Среднее квадратическое отклонение выборки A: {s1}\nСреднее квадратическое отклонение выборки B: {s2}')

Объём выборки A: 2509
Объём выборки B: 1465
Среднее квадратическое отклонение выборки A: 0.17250951379621335
Среднее квадратическое отклонение выборки B: 0.19825513126725994


In [62]:
# найдём среднее квадратическое отклонение разности между выборочными средними выборок A и B:

s_delta = np.sqrt(s1 ** 2 / n1 + s2 ** 2 / n2)

s_delta

0.006220171278295827

In [63]:
# посчитаем значение статистики:

t = (a.mean() - b.mean()) / s_delta

t

-1.6504551408398205

In [64]:
# определим число степеней свободы распределения:

df = (s1 ** 2 / n1 + s2 ** 2 / n2) ** 2 / ((s1 ** 2 / n1) ** 2 / (n1 - 1) + (s2 ** 2 / n2) ** 2 / (n2 - 1))

df

2732.802564435212

In [65]:
alpha = 0.05 # уровень значимости

# считаем квантили:

t1 = stats.t.ppf(alpha / 2, df=df)
t2 = stats.t.ppf(1 - alpha / 2, df=df)

t1, t2

(-1.9608324352746576, 1.9608324352746571)

In [66]:
# проверим значение статистики при помощи stats.ttest_ind, убедимся, что оно такое же:

stats.ttest_ind(a, b, equal_var=False)

Ttest_indResult(statistic=-1.6504551408398205, pvalue=0.09896479217925899)

In [67]:
# за нулевую гипотезу берётся предположение, что конверсия на страницах A и B не отличается.
# видим, что статистика не попадает в критическую область, соответственно, нет основания отвергать H0.
# таким образом, отличие конверсии на страницах A и B не является значимым.

if t < t1 or t > t2:
    print('Ответ: 1')
elif t1 < t < t2:
    print('Ответ: 0')

Ответ: 0
